### ISSUE TITLE
Configuration info.

### ISSUE THREAD

**Issue by JoseAgustin** [indico/indico-plugins#142]
I would like to change the setting for my institution but I was no able to find in which file I have to do that.

> These are the most relevant configuration options:
> Notification email addresses - Additional e-mails which will receive notifications
> E-mail domains - List of e-mail domains which can be used for the Zoom API (e.g. cern.ch)
> Webhook token (optional) - the token which Zoom requests will authenticate with (get it from Zoom Marketplace)

**Comment by ThiefMaster** [comment]
it's in the Admin area under Plugins
