### ISSUE TITLE
String defect

### ISSUE THREAD

**Issue by adavidzh** [indico/indico-plugins#144]
Regarding https://github.com/indico/indico-plugins/blob/8f2d8114a318bb8ab9c35d075c6c0ed6e26a96e0/citadel/indico_citadel/search.py#L95
and/or
https://github.com/indico/indico-plugins/blob/af13760a01b57938b952338aa610f3b615144e25/citadel/indico_citadel/translations/messages.pot#L102

I thought I'd just note that this is not a sentence right now. Let me know if you prefer a PR instead of just an issue.

**Comment by ThiefMaster** [comment]
Thanks, fixed.

PS: A PR would have been find for this as well ;)

**Comment by ThiefMaster** [comment]
> I was not sure why the same information appears in two places

We're using gettext-style i18n, so the string in the code is the source string; the pot file is what will be used by translators (we usually update it from time to time and ignore it during day-to-day development as it does not need to be fully up to date all the time).

**Comment by adavidzh** [comment]
I see. Now that I saw your commit, I see that the `pot` file is somehow derived.

So, just in case I spot more #TyposInTheWild I can just PR against the non-`pot` files?

**Comment by ThiefMaster** [comment]
yep, the pot file can be safely ignored (but no harm in changing the typo there as well)
