### ISSUE TITLE
i18n strings not referenced from Admin interface

### ISSUE THREAD

**Issue by vaclavstepan** [indico/indico-plugins#152]
### Issue

It seems the zoom plugin administration interface (admin/plugins/vc_zoom/) is not using localized strings.
They are defined in Transifex, but even when they are translated, US English version is displayed in the inteface.

### How to reproduce

1. Switch to non-English language
2. In Indico administration, open Zoom plugin page
3. See most of the strings staying in English

**Comment by ThiefMaster** [comment]
Which language are you testing with?

**Comment by vaclavstepan** [comment]
Oh. You are right, I was not pulling the vc-zoom translation file correctly. My mistake and my apologies.
