### ISSUE TITLE
[NEW Plugin Request] Zoom Videoconferencing

### ISSUE THREAD

**Issue by juztas** [indico/indico-plugins#76]
Hi,

It would be great to have a Zoom plugin implementation together with Indico. 
As Basic - having the ability to add information to the event about the join URL and additional phone numbers is enough;
As Extended - automatically create the room and populate this information from zoom to indico would be awesome.

**Comment by ThiefMaster** [comment]
If someone contributed such a plugin that'd be great! No need for it to be an official plugin by us (that would only happen if CERN used Zoom - but we are currently using Vidyo, so we can't spend resources on developing a plugin for something we don't even use ourselves) - someone from the community could develop one (we'd provide help of course when there are any questions or questions about the architecture etc.), and then release it as a stand-alone plugin (like others did for Stripe payments for example).

**Comment by mschnepf** [comment]
CERN now also has a ZOOM license, and it looks like it is used a lot.
So it would be nice if Indico supports ZOOM.
Are there some plans to do it?

**Comment by ThiefMaster** [comment]
Hi, someone started working on a plugin here: https://talk.getindico.io/t/zoom-videoconference-plug-in/1752/3

We are going to test this plugin and possibly polish it and eventually make it official (of course only if CERN ends up going for Zoom in the end!)

**Comment by knutzk** [comment]
Hi all, I'm just curious if there has been any update regarding this plugin request? As far as I can tell, most of the large-scale meetings at CERN are already on Zoom and also smaller CERN-internal meetings have started switching. So even without an official transition to Zoom, I'm sure there would be a lot of interest to have a stand-alone plugin :-)

**Comment by hormiai76** [comment]
Hi,
Some users at MAXIV started asking if it's possible to use Zoom in the Indico events... any news?
Alberto Nardella

**Comment by ThiefMaster** [comment]
Closing since we have a Zoom plugin (added in #90, just needs to be released as a "stable" version instead of the prerelease we have right now).
