### ISSUE TITLE
RFC: Deprecating some old plugins / moving them to an attic repo?

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico-plugins#77]
We have some plugins which we aren't using anymore and thus don't really spend time on maintaining; and chances are good the community isn't actively using them either.

Should we move those into a separate repo (e.g. `indico-plugins-attic`), and also remove them (if currently included) from the `indico-plugins` meta package?

Good candidates for that would be:

- `chat` - Jabber isn't really a thing anymore, we also don't use it, and except for obvious things that need fixing after refactoring things in the code (which are usually only found by searching in the codebase, not by actually testing the plugin) it's unmaintained
- `search-invenio` - known to be broken since 2.1 or earlier. Never released on PyPI either. 
- `livesync-invenio` - not really useful without `search-invenio`; not actively used, probably not working with latest invenio, uses very legacy (marcxml) serialization logic from the core
- `storage-xrootd` - EOS/XrootD for storage is not really used anywhere except at CERN, and we stopped using it for Indico (besides a small instance that still needs to be moved to s3 object storage)

cc @pferreir

**Comment by ThiefMaster** [comment]
These plugins are now in the [attic repo](https://github.com/indico/indico-plugins-attic).

**Comment by ThiefMaster** [comment]
@mic4ael Can you check if there's away to archive (but not delete) the resources of these plugins on Transifex so people don't waste time translating them?

**Comment by mic4ael** [comment]
Done. From now on, translators will not be able to add/edit translations for these plugins.
