### ISSUE TITLE
CERN Indico Event Statistics Broken

### ISSUE THREAD

**Issue by graeme-a-stewart** [indico/indico-plugins#84]
**Describe the bug**
The event summary statistics on CERN Indico clearly do not work.

**To Reproduce**
Following the following URL to get statistics on our workshop from last month:

<https://indico.cern.ch/event/908146/manage/statistics/?start_date=2020-05-01&end_date=2020-06-08>

Indico reports 0 visitors, which is clearly nonsense for an event with over 200 people registered (see screenshot).

It's also inconsistent with the default query window (2020-04-29 to 2020-05-13), which lists 593 visitors (second screenshot).

**Expected behavior**
Give reliable data.

In particular it's very desirable for us, as organisers, to see how often the videos of the event were viewed.

**Screenshots**
![Screenshot 2020-06-08 at 13 05 27](https://user-images.githubusercontent.com/8511620/84023816-1075f100-a989-11ea-8760-1b28e5b600ba.png)
![Screenshot 2020-06-08 at 13 07 33](https://user-images.githubusercontent.com/8511620/84023824-14a20e80-a989-11ea-82f3-3d98bdb7c77f.png)

**Comment by ThiefMaster** [comment]
To me it looks like it failed to load data from the Piwik APIs. When I open the URL you posted I see correct data, but it took a few page reloads until I got that - before I also saw the empty list.

Unfortunately this means we cannot really fix it; all we could do is maybe adding better error handling to show clearly when loading the data failed.

**Comment by graeme-a-stewart** [comment]
Hi - yes, I see what you mean. I got more credible numbers on a reload.

I still think there's an issue there, however. When I look at the stats for one of the event video files, it gives me 0 accesses

https://indico.cern.ch/event/908146/contributions/3826737/attachments/2032717/3411822/01_code_portability.mp4

I know for a fact that I looked at that video file several times.

Video is obviously hard (maybe people skip bits, watch half, etc.), but 0 accesses seems unlikely. (I note in passing that another workshop said that their YouTube uploads were much more popular than the videos on Indico, but I do wonder if Indico is undereporting?)

**Comment by ThiefMaster** [comment]
Yes, material download tracking is broken. I honestly don't remember why (we've been in contact with the Piwik guys a few years ago) and the conclusion was that Piwik is not suitable for this.

We need to move it to local tracking of downloads (best option, simply incrementing a counter for every download) or just remove it altogether.

**Comment by ThiefMaster** [comment]
Closing as we removed the broken material download tracker over a year ago...
